// Re-export all types from the split modules for backwards compatibility.
// Any file importing from './types' or './types.js' will continue to work.
export type {
  BetterStripeOptions,
  FeeOverride,
  FeeTier,
  PlatformFeeConfig,
  RegisterRoutesConfig,
  StripeWebhookEvent,
  StripeEventHandler,
  StripeEventHandlers,
  WebhookActionCtx,
  V2ThinEvent,
  AccountLinkWithStatus,
  PaymentMethodCard,
  PaymentMethodLike,
  StripeComponentAccount,
  StripeComponentPayment,
  StripeComponentPayout,
  StripeComponentRefund,
  StripeComponentDispute,
  StripeComponentWebhookEvent,
  StripeComponentProduct,
  StripeComponentPrice,
  StripeComponentSubscription,
  StripeComponentCheckoutSession,
  StripeComponentInvoice,
  StripeCountrySpecs,
  StripeV2Account,
  SyncTriggers,
  SyncTriggerCtx,
  AsyncHooks,
  AsyncHookCtx,
  WebhookHandlerRefs,
} from "./types/index.js";
